### PR TITLE
Update Discord.php

### PR DESCRIPTION
**Pull request by Lier0**
Fix https://cdn.discordapp.com/avatars/0.png, ie discord user without avatar trying to sign in.

### CODE REVIEW

**Comment by datitisev** [comment]
This looks good to me. Not tested locally but I don't see anything wrong. The code could be simplified - `https://cdn.discordapp.com/avatars/{$user->getId()}/{$user->getAvatarHash()}.png` I think, but that's fine.

**Comment by Lier0** [comment]
Like this last commit you mean ?

**Comment by datitisev** [comment]
Yeah that's good!

**Comment by clarkwinkelmann** [comment]
Thanks for the PR! I tested locally and will include this in the next release.

**Pull request merged**
