### PR TITLE
Google branding

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
A simplified version of the Google part of #13 

I have already pushed all the fixes unrelated to Google on `master`.

Since Google only appears to require the base color and width/height, I have preserved as much of the original Flarum button as possible. The little blue border/padding around the button doesn't seem required but I've kept it because it looks nicer.

I have changed the way the font is loaded so that it's only loaded when the Google provider is active.

image

image

### CODE REVIEW

**Comment by matteocontrini** [comment]
Wouldn't it perhaps be better to have a white button for Google? Discourse does it that way and it allows to keep a coherent styling among buttons:

image

They also don't use Roboto (that seems a ridiculous requirement to me) so probably Google doesn't enforce that.

**Comment by clarkwinkelmann** [comment]
True, we could use white.

I have really no idea if/how Google enforces it, but Roboto is part of the requirements as much as the dimensions.

There's some very conflicting info about the scale. The way it's defined it seems 40px tall is acceptable. The one generated by their own library however is 48px tall. And the one in your screenshot probably isn't 40px tall :thinking:

**Comment by matteocontrini** [comment]
> I have really no idea if/how Google enforces it, but Roboto is part of the requirements as much as the dimensions.

I've seen that (for others reading, [here](https://developers.google.com/identity/branding-guidelines)) but if it doesn't play a role in the ability to use Sign in with Google in practice... Does it actually matter? 😬 

I've checked some websites and none of them follow the guidelines:

- LogDNA.com, random styling:

image

- Trello, 40px tall but wrong font:

image

- WordPress.com, 40px tall but wrong font:

image

- Auth0.com, 50px tall but wrong font:

image

What about making all the buttons 40px tall so that they're uniform, and guidelines are respected?

For the font thing, to be honest, it would stop me from enabling Google login, it seems an unnecessary requirement that would only slow down page load... It seems that not even Google is respecting its own guidelines. For example, on Pinterest.com the Google button is an iframe from Google and it doesn't use Roboto 😶

**Comment by datitisev** [comment]
Whatever way we go with, I think the "Log In with Google" button should be in a new line regardless of if the flex layout is enabled. It does not look good having the circular buttons & google one in the same line.

**Comment by clarkwinkelmann** [comment]
The original idea for this PR was to re-use as much as possible from the existing successful implementation by @luuhai48 

However it's true we could discuss a more Flarum integrated solution that follows Google guidelines a little less closely

If I switch to white and remove almost everything specific to Google, I get this:

(the code for this is not pushed to this PR)

image

It still very closely matches every requirement, except the font.

I have applied the same margin between icon and text for all icons instead of just Google.

I'm not sure about the inline thing. Sure, it would look nice, but kind of negate the reason there's an inline theme... If you have only two login providers, you might as well use the default layout already.

image

**Comment by matteocontrini** [comment]
That looks much nicer, approved! 😄

**Comment by datitisev** [comment]
> I'm not sure about the inline thing. Sure, it would look nice, but kind of negate the reason there's an inline theme

Well, the point of it was less an inline theme and more rounded icons for providers. As that cannot be done with Google, it should go in its own line - specially cause if not it looks terrible? Why would we want it to look like thst regardless of the point? And this cna be easily done with CSS and nothing else so it shouldn't be that much of an issue - forum owners could easily override it.

**Comment by luceos** [comment]
I am against the inline version, and you could probably customise that with some css hacking if you really wanted that.

Can we get the https://github.com/FriendsOfFlarum/oauth/pull/18#issuecomment-761607111 first version in and merged?

**Comment by clarkwinkelmann** [comment]
Ok I'll go with the completely white background and will make it have its own line.

I just need to tweak the CSS because it's flex and display:block doesn't change anything, and setting the width isn't enough or has to be 100% of width which doesn't look good either.

**Pull request merged**
