### PR TITLE
Url for the applications has been changed

### PR DESCRIPTION
**Pull request by Justman10000**
Test on a loose version was successful

### CODE REVIEW

**Comment by Justman10000** [comment]
@imorland

**Comment by imorland** [comment]
What do you mean by a `loose` version? Can you provide any link to documentation where this change was made by GitLab?

**Comment by Justman10000** [comment]
> Can you provide any link to documentation where this change was made by GitLab?

Like right now? Just go to both links... The first one doesn't work!

**Comment by Justman10000** [comment]
> Can you provide any link to documentation where this change was made by GitLab?

Like right now? Just go to both links... The actual one doesn't work!

**Comment by imorland** [comment]
> > Can you provide any link to documentation where this change was made by GitLab?
> 
> 
> 
> Like right now? Just go to both links... The actual one doesn't work!

That assumes I have a gitlab account, which I don't, so I'll need to verify in some way else!

**Comment by datitisev** [comment]
@Justman10000 is correct. I remember this being brought up in the past, and I thought I had fixed it... That may have been something else 🤷

**Review by datitisev — APPROVED** [review]

**Comment by Justman10000** [comment]
> > > Can you provide any link to documentation where this change was made by GitLab?
> > 
> > 
> > Like right now? Just go to both links... The actual one doesn't work!
> 
> That assumes I have a gitlab account, which I don't, so I'll need to verify in some way else!

It works without...
<br>

[Current link](https://gitlab.com/profile/applications)
grafik

[New Link](https://gitlab.com/-/profile/applications)
grafik

**Comment by imorland** [comment]
> It works without...

Actually, it doesn't. Both URLs redirect to a login page, so for someone without an account it's not possible to verify...

image

However, as @datitisev has also confirmed this change is correct, I'm happy to approve this change.

**Review by imorland — APPROVED** [review]

**Pull request merged**
